services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    networks:
      - my_network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  my_network: